import {SOURCES,makeCase,Workflow,notice,yen,GROUP_LABELS} from './engine.js';
const $=s=>document.querySelector(s), esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let workflow=new Workflow(), fixture=makeCase(), busy=false, runToken=0;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelector('#case-view').hidden=b.dataset.view!=='case';document.querySelector('#sources-view').hidden=b.dataset.view!=='sources';document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===b));});
$('#source-links').innerHTML=SOURCES.map(s=>`<div class="source"><a href="${s.url}" target="_blank" rel="noopener">${esc(s.title)} ↗</a><p>${esc(s.note)}</p></div>`).join('');
function input(){return {name:$('#name').value.trim(),month:$('#month').value,age:Number($('#age').value),provider:$('#provider').value.trim(),total:Number($('#total').value),paid:Number($('#paid').value),excluded:Number($('#excluded').value),identity:$('#identity').checked};}
function fill(){Object.entries(fixture.input).forEach(([k,v])=>{if(k==='identity')$('#'+k).checked=v;else $('#'+k).value=v;});const r=fixture.reference;$('#reference-data').innerHTML='<dl>'+[['世帯ID',r.householdId],['診療月',r.month],['国保資格','確認済み（模擬）'],['旧ただし書所得',yen(r.income)],['レセプト',r.receiptArrived?'審査確定（模擬）':'未到着'],['台帳の総医療費',yen(r.receiptTotal)],['台帳の支払額',yen(r.receiptPaid)],['過去の該当月',r.history.join(' / ')||'なし'],['8月起算の確定累計',yen(r.annualRetained)]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')+'</dl>';$('#case-id').textContent=r.householdId;}
function log(events){$('#trace').innerHTML=events.length?events.map((e,i)=>`<div class="event"><span class="step-icon">${i+1}</span><div><b>${esc(e.title)}</b><p>${esc(e.detail)}</p>${e.source?`<a href="${SOURCES.find(s=>s.id===e.source)?.url}" target="_blank" rel="noopener">根拠資料 ↗</a>`:''}</div></div>`).join(''):'<p class="muted">各処理の結果と根拠を記録します。</p>';}
function clear(){runToken++;busy=false;workflow.invalidate();$('#run').disabled=false;$('#run').classList.remove('running');$('#run').textContent='エージェントで審査する →';$('#form-error').textContent='';render();}
function render(){const c=workflow.current;const state=c?.state;const status={ready:'決裁待ち',zero:'0円・決裁待ち',review:'職員確認が必要',approved:'決裁済み',paid:'模擬振込完了'};$('#status').textContent=status[state]||'受付待ち';$('#status').className='pill '+(state==='review'?'warn':state?'good':'');$('#flow').querySelectorAll('li').forEach((li,i)=>li.classList.toggle('done',!!c&&i<=(['approved','paid'].includes(state)?state==='paid'?3:2:1)));$('#actions').innerHTML='';
 if(!c){$('#result-content').innerHTML='<div class="empty"><span class="empty-icon">↗</span><h3>申請を確認して、審査を開始</h3><p>照会結果・計算式・次に必要な手続きを<br>エージェントがここにまとめます。</p></div>';log([]);$('#output-content').innerHTML='<span class="muted">審査後に確認依頼・審査記録、決裁後に通知書と模擬振込データを出力できます。</span>';return;}
 const r=c.result;
 if(state==='review'){$('#result-content').innerHTML=`<div class="notice"><b>自動処理を保留しました</b><p>次の確認を終えてから、申請を再審査してください。</p><ul>${r.blockers.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>${r.amount!==null?`<p class="field-note" style="margin-top:15px">月額だけの参考試算：${yen(r.amount)}。支給決定額ではありません。</p>`:''}`;}
 else{$('#result-content').innerHTML=`<div class="result-hero"><div class="money-label">${['approved','paid'].includes(state)?'支給決定額（模擬）':'払い戻し額（決定案）'}</div><div class="money">${r.amount.toLocaleString('ja-JP')}<small>円</small></div></div><dl><div><dt>保険診療の支払済額</dt><dd>${yen(c.input.paid)}</dd></div><div><dt>適用後の自己負担</dt><dd>${yen(r.cap)}</dd></div><div><dt>所得区分 / 回数</dt><dd>区分${GROUP_LABELS[r.group]} / ${r.multiple?'多数回該当':'通常'}</dd></div><div><dt>対象外費用（除外済み）</dt><dd>${yen(c.input.excluded)}</dd></div></dl><div class="formula">限度額の計算<strong>${esc(r.formula)}</strong></div><p class="field-note">適用ルール：${esc(r.version)}<br>${state==='paid'?'模擬振込が完了しました。実際の送金はありません。':state==='approved'?'職員決裁済み。通知書の確認・出力ができます。':'照会・照合を完了しました。内容を確認し、職員決裁に進んでください。'}</p>`;}
 if(['ready','zero'].includes(state)){$('#actions').innerHTML='<label style="font-size:14px;width:100%">決裁者（模擬）<input id="reviewer" placeholder="例：国保担当 佐藤" value="国保担当 佐藤（架空）" maxlength="60"></label><button class="primary" id="approve">内容を確認して決裁する</button>';$('#approve').onclick=()=>act(()=>workflow.approve($('#reviewer').value));}
 if(state==='approved'&&r.amount>0){$('#actions').innerHTML='<button class="primary" id="pay">模擬振込を実行する →</button>';$('#pay').onclick=()=>act(()=>workflow.pay());}
 log(c.events);renderOutputs();
}
function act(fn){try{fn();$('#form-error').textContent='';render();}catch(e){$('#form-error').textContent=e.message;}}
function download(name,body,type){const u=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function record(){const c=workflow.current;return {...c,scope:'単独・18〜69歳・3割負担・単一レセプト・償還払い',warning:'PoCのみ。生成AIと実システムは未接続。永続監査証跡ではありません。',sources:SOURCES};}
function renderOutputs(){const c=workflow.current;const approved=['approved','paid'].includes(c.state);$('#output-content').innerHTML=`<div class="download-row"><button id="json">審査・実行記録 JSON ↓</button>${c.state==='review'?'<button id="review-note">確認依頼 TXT ↓</button>':''}${approved?'<button id="notice">通知書 TXT ↓</button><button id="print">通知書を印刷 / PDF</button>':''}${c.state==='paid'?'<button id="csv">模擬振込 CSV ↓</button>':''}</div>${approved?'<pre class="output-preview" id="notice-preview"></pre>':'<p class="field-note" style="margin-top:15px">支給通知書は職員決裁後に作成します。</p>'}`;
 $('#json').onclick=()=>download(c.id+'-audit.json',JSON.stringify(record(),null,2),'application/json');
 if(c.state==='review')$('#review-note').onclick=()=>download(c.id+'-review.txt',`【PoC・職員確認依頼】\n受付番号：${c.id}\n申請者：${c.input.name}\n対象月：${c.input.month}\n\n${c.result.blockers.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n確認後に再審査してください。正式な通知ではありません。`,'text/plain;charset=utf-8');
 if(approved){$('#notice-preview').textContent=notice(c);$('#notice').onclick=()=>download(c.id+'-notice.txt',notice(c),'text/plain;charset=utf-8');$('#print').onclick=()=>window.print();}
 if(c.state==='paid')$('#csv').onclick=()=>{const p=c.payment;download(c.id+'-payment.csv','\uFEFFmode,payment_id,idempotency_key,account_token,amount_yen,status,real_transfer\r\n'+['simulation',p.id,p.idempotencyKey,p.accountToken,p.amount,p.status,false].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')+'\r\n','text/csv;charset=utf-8');};
}
async function run(){if(busy)throw new Error('審査中です。');if(!$('#claim-form').reportValidity())throw new Error('入力項目を確認してください。');busy=true;const token=++runToken;$('#run').disabled=true;$('#run').classList.add('running');$('#run').textContent='照会・審査を実行中…';$('#status').textContent='審査中';$('#form-error').textContent='';const c=workflow.run(input(),fixture.reference);$('#actions').innerHTML='';$('#output-content').textContent='審査中…';
 for(let i=1;i<=c.events.length;i++){if(token!==runToken)return {cancelled:true};log(c.events.slice(0,i));await new Promise(resolve=>setTimeout(resolve,120));}
 if(token!==runToken)return {cancelled:true};busy=false;$('#run').disabled=false;$('#run').classList.remove('running');$('#run').textContent='エージェントで再審査する →';render();return {id:c.id,state:c.state,amount:c.result.amount,blockers:c.result.blockers};}
$('#claim-form').onsubmit=e=>{e.preventDefault();run().catch(e=>{busy=false;$('#run').disabled=false;$('#form-error').textContent=e.message;});};
$('#claim-form').oninput=()=>{clear();};
$('#scenario').onchange=()=>{fixture=makeCase($('#scenario').value);fill();clear();};
$('#reset').onclick=()=>{workflow=new Workflow();fixture=makeCase($('#scenario').value);fill();clear();};
fill();render();
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();const tools=[
 {name:'read_benefit_case',title:'申請・審査結果を読む',description:'現在表示している検証ケース、模擬照会台帳、審査結果を取得。実データではありません。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:args=>{if(!args||Object.keys(args).length)throw new Error('引数は空オブジェクトです。');return {input:input(),reference:fixture.reference,state:workflow.current?.state||'draft',result:workflow.current?.result||null};}},
 {name:'run_benefit_review',title:'高額療養費を審査する',description:'表示中の構造化申請を模擬照会とルールエンジンで審査し、決裁待ちまたは職員確認へ進める。決裁・送金は行わない。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:args=>{if(!args||Object.keys(args).length)throw new Error('引数は空オブジェクトです。');return run();}},
 {name:'stage_benefit_scenario',title:'検証ケースを選択する',description:'指定した架空申請ケースを画面に読み込み、現在の審査・決裁を無効にする。支払済みの重複記録は維持する。',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:['standard','old','multiple','missing','below','unsupported','annual']}},required:['scenario'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:args=>{if(!args||Object.keys(args).length!==1||!['standard','old','multiple','missing','below','unsupported','annual'].includes(args.scenario))throw new Error('無効な検証ケースです。');$('#scenario').value=args.scenario;fixture=makeCase(args.scenario);fill();clear();return {scenario:args.scenario,state:'draft'};}}
 ];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
