import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeCase,evaluate,Workflow,groupFor,notice} from '../dist/engine.js';
const calc=(type='standard',patch={},ref={})=>{const c=makeCase(type);return evaluate({...c.input,...patch},{...c.reference,...ref});};
test('2026年8月の標準申請: 300000 - 92940 = 207060',()=>{const r=calc();assert.equal(r.status,'ready');assert.equal(r.cap,92940);assert.equal(r.amount,207060);});
test('改正前7月: 212570円',()=>assert.equal(calc('old').amount,212570));
test('多数回: 255600円',()=>assert.equal(calc('multiple').amount,255600));
test('上限未満: 0円',()=>{assert.equal(calc('below').amount,0);assert.equal(calc('below').status,'zero');});
test('不足・年齢・年間上限は決裁に進めない',()=>{for(const type of ['missing','unsupported','annual'])assert.equal(calc(type).status,'review');});
test('入力変更の照合不一致',()=>assert.equal(calc('standard',{paid:299999}).status,'review'));
test('未確認情報を推定しない',()=>{for(const key of ['incomeVerified','historyVerified','annualVerified','eligible','bankVerified'])assert.equal(calc('standard',{}, {[key]:false}).status,'review');});
test('診療月境界と未対応月',()=>{for(const m of ['2025-12','2027-08','2026-13',''])assert.equal(calc('standard',{month:m},{month:m}).status,'review');for(const m of ['2026-01','2026-07','2026-08','2027-07'])assert.equal(calc('standard',{month:m},{month:m}).status,'ready');});
test('所得境界',()=>{for(const [income,expected]of [[0,'d'],[2100000,'d'],[2100001,'c'],[6000000,'c'],[6000001,'b'],[9010000,'b'],[9010001,'a']])assert.equal(groupFor({income,taxExempt:false}),expected);assert.equal(groupFor({income:0,taxExempt:true}),'e');});
test('新制度の全区分',()=>{for(const [income,taxExempt,cap]of [[10000000,false,271290],[7000000,false,183130],[3500000,false,92940],[2000000,false,61500],[0,true,36900]])assert.equal(calc('standard',{}, {income,taxExempt}).cap,cap);});
test('過去11か月のdistinct月だけカウント',()=>{assert.equal(calc('standard',{}, {history:['2025-08','2026-04','2026-04','2026-05','2026-08','2026-09']}).multiple,false);assert.equal(calc('standard',{}, {history:['2025-09','2026-04','2026-05']}).multiple,true);});
test('対象外費用は支給額に影響しない',()=>assert.equal(calc('standard',{excluded:500000}).amount,207060));
test('金額異常・例外は保留',()=>{for(const value of [-1,NaN,Infinity,1.5,100000001])assert.equal(calc('standard',{total:value}).status,'review');for(const ref of [{receiptCount:2},{householdMembers:2},{benefitInKind:1},{publicAid:true},{insurerChanged:true},{incomeChanged:true}])assert.equal(calc('standard',{},ref).status,'review');});
test('端数は専門審査',()=>assert.equal(calc('standard',{total:1000010,paid:300003},{receiptTotal:1000010,receiptPaid:300003}).status,'review'));
test('決裁と模擬支払・二重支給防止',()=>{const w=new Workflow(),c=makeCase();assert.throws(()=>w.pay());w.run(c.input,c.reference);assert.throws(()=>w.pay());assert.throws(()=>notice(w.current));assert.throws(()=>w.approve(''));w.approve('担当職員');assert.match(notice(w.current),/207,060円/);w.pay();assert.equal(w.current.payment.realTransfer,false);assert.throws(()=>w.pay());w.run(c.input,c.reference);assert.equal(w.current.state,'review');assert.throws(()=>w.approve('担当職員'));});
test('0円には送金なし・編集時は決裁失効',()=>{const w=new Workflow(),c=makeCase('below');w.run(c.input,c.reference);w.approve('担当');assert.throws(()=>w.pay());w.invalidate();assert.throws(()=>w.approve('担当'));});
