import test from 'node:test';import assert from 'node:assert/strict';
import {annualCase,annualCases} from './annual-fixtures.mjs';import {processCase} from './process.mjs';import {evaluateAnnual} from './annual.mjs';import {searchIssue} from './retrieval.mjs';import {sectionsFor} from './knowledge/manifest.mjs';import {readFileSync} from 'node:fs';
const expected={'ANNUAL-LOW2':36000,'ANNUAL-GENERAL':48000,'ANNUAL-OLD-OUT':72000,'ANNUAL-YOUNG-C':70000,'ANNUAL-LOW200':70000,'ANNUAL-PAID':26000,'ANNUAL-LOW1':8400};
for(const row of annualCases())test(row.id+' 独立した期待額',()=>{const r=processCase(row);assert.deepEqual(r.findings,[]);assert.equal(r.annual.additional,expected[row.id]);assert.equal(r.monthly.additional,0);assert.equal(r.conclusion,'還付見込みあり');if(row.id==='ANNUAL-LOW200')assert.equal(r.annual.not_before,'2027-08-01');});
const check=(mutate,kind='MISSING_FACT')=>{const r=annualCase();mutate(r);const out=processCase(r);assert.equal(out.annual,null);assert.ok(out.findings.some(f=>f.kind===kind));return out;};
test('年度途中で未来の年間給付を確定しない',()=>check(r=>r.payload.simulation_date='2026-09-20'));
test('7月31日中は年度終了後とは扱わない',()=>check(r=>r.payload.simulation_date='2027-07-31'));
test('41万円特例の確認証拠を必須とする',()=>{const r=annualCase({group:'general'});delete r.payload.facts.annual.low_income_200_evidence;assert.equal(processCase(r).annual,null);});
test('2027年8月以降を2026年改正の式で計算しない',()=>{const r=annualCase({year:2027});const out=processCase(r);assert.equal(out.monthly,null);assert.equal(out.annual,null);assert.ok(out.findings.some(f=>f.id==='period'));});
test('欠落月を0円にしない',()=>check(r=>r.payload.facts.annual.months.pop()));
test('重複月を集計しない',()=>check(r=>r.payload.facts.annual.months[0].month=r.payload.month,'INVALID_FACT'));
test('所得区分変更を現行区分で上書きしない',()=>check(r=>r.payload.facts.annual.months[0].facts.income.senior='general'));
test('保険者変更は継続性を推測しない',()=>check(r=>r.payload.facts.annual.months[0].facts.qualification.insurer='OTHER'));
test('修正後は年間台帳との照合で停止',()=>check(r=>{r.payload.facts.annual.months[11].facts.statements[0].cash=10000;},'INVALID_FACT'));
test('既支給超過を0円に丸めない',()=>check(r=>r.payload.facts.annual.prior_paid=50000,'INVALID_FACT'));
test('証拠のない月別明細は計算しない',()=>check(r=>r.payload.facts.annual.months[0].verified=false));
test('複数家族の年間給付配賦を創作しない',()=>{const r=annualCase();r.payload.facts.qualification.members.push({...r.payload.facts.qualification.members[0],id:'FAMILY'});const out=evaluateAnnual(r.payload.month,r.payload.facts,{asOf:'2027-08-01'});assert.equal(out.findings[0].kind,'RULE_GAP');});
test('年間対象を暦年にしない',()=>check(r=>r.payload.facts.annual.from='2027-01','INVALID_FACT'));
test('月額給付・現物給付を再度控除しない',()=>{const r=annualCase({cash:20000});for(const m of r.payload.facts.annual.months){const s=m.facts.statements[0];s.cash=11000;s.in_kind=9000;}Object.assign(r.payload.facts.statements[0],r.payload.facts.annual.months[11].facts.statements[0]);r.payload.draft=structuredClone(r.payload.facts.statements);const out=processCase(r);assert.equal(out.monthly.additional,0);assert.equal(out.annual.additional,36000);});
const corpus=sectionsFor(JSON.parse(readFileSync(new URL('./knowledge/sections.json',import.meta.url))));
for(const [month,allowed,forbidden] of [['2026-07',['overview-4','guide-5'],['reform-4','reform-5','overview-2','overview-3']],['2026-08',['reform-4','overview-2'],['reform-5','overview-3','overview-4']],['2027-07',['reform-4','overview-2'],['reform-5','overview-3']],['2027-08',['reform-5','overview-3'],['reform-4','overview-2']]])test('根拠適用月 '+month,()=>{const hits=searchIssue({id:'P32'},{month,members:[{age:45}]},corpus).hits;assert.ok(hits.some(h=>allowed.includes(h.id)));assert.ok(hits.every(h=>!forbidden.includes(h.id)));assert.ok(hits.every(h=>!['reform-6','overview-18'].includes(h.id)));});
