import test from 'node:test';import assert from 'node:assert/strict';
import {Store} from './store.mjs';import {Agent} from './agent.mjs';import {seed,scope} from './fixtures.mjs';import {PATTERNS} from './catalog.mjs';
function setup(t,options){const store=new Store();t.after(()=>store.close());const facts=seed(store,options);return {store,facts,agent:new Agent({store})};}
test('32パターンを漏れなく登録し未実装を区別',()=>{assert.equal(PATTERNS.length,32);assert.equal(new Set(PATTERNS.map(p=>p.id)).size,32);assert.equal(PATTERNS[29].status,'ANNUAL_WITH_PRECONDITIONS');});
test('DB→文書→職員依頼→DB回答→月額計算→再実行',async t=>{
 const {store,facts,agent}=setup(t,{omit:['income']});let r=await agent.run(scope);assert.equal(r.state,'WAITING_STAFF');assert.equal(r.proposal,null);assert.equal(r.next_action.issue_id,'income');
 await agent.run(scope);assert.equal(store.db.prepare('SELECT COUNT(*) n FROM outbox').get().n,1);
 store.put(scope,'income',facts.income,{evidence:'DEMO-ANSWER'});r=await agent.run(scope);assert.equal(r.state,'MONTHLY_PROPOSAL');assert.equal(r.proposal.additional,212570);
 assert.equal(store.db.prepare('SELECT status FROM outbox').get().status,'SUPERSEDED');assert.equal((await agent.run(scope)).reused,true);
 const events=store.db.prepare('SELECT kind FROM events ORDER BY seq').all().map(r=>r.kind);assert.deepEqual(events.slice(0,4),['DB_READ','RULES_EVALUATED','DOCUMENTS_READ','REQUEST_PREPARED']);
});
test('本人資料の不足は国民への照会案を保存し送信しない',async t=>{const {agent,store}=setup(t,{omit:['statements']});const r=await agent.run(scope);assert.equal(r.state,'WAITING_CITIZEN_REQUEST_APPROVAL');assert.equal(JSON.parse(store.db.prepare('SELECT payload FROM outbox').get().payload).sent,false);});
test('DBに必要情報が揃えばAIを呼ばず計算',async t=>{const {store}=setup(t);const agent=new Agent({store,planner:{version:'test',choose(){throw Error('呼ばれてはいけない');}}});assert.equal((await agent.run(scope)).state,'MONTHLY_PROPOSAL');assert.equal(store.db.prepare("SELECT COUNT(*) n FROM events WHERE kind='DOCUMENTS_READ'").get().n,0);});
test('AIは文書から許可された次の行動を選び照会案を保存できる',async t=>{const {store}=setup(t,{omit:['income']});let called=false;const agent=new Agent({store,planner:{version:'test',choose:async context=>{called=true;assert(context.documents.length);return {option_id:'0',question:'対象月の認定所得区分を回答してください。',source_ids:['guide']};}}});const r=await agent.run(scope);assert(called);assert.equal(r.next_action.generator,'AI');assert.equal(r.next_action.recipient,'STAFF');});
test('AIによる支給額や外部送信の指示を採用しない',async t=>{const {store}=setup(t,{omit:['income']});const agent=new Agent({store,planner:{version:'test',choose:async()=>({option_id:'0',question:'送信',source_ids:['guide'],payment:300000})}});const r=await agent.run(scope);assert.equal(r.next_action.generator,'DETERMINISTIC_FALLBACK');assert.equal(r.proposal,null);});
test('別ユーザー・別テナントの資料を混ぜない',async t=>{const {agent}=setup(t);for(const change of [{user_id:'OTHER'},{tenant:'OTHER'}]){const r=await agent.run({...scope,...change});assert.equal(r.proposal,null);assert(r.findings.some(f=>f.id==='statements'));}});
test('例外有無が未確認なら非該当と推測しない',async t=>{const {store,agent}=setup(t);store.put(scope,'exception_screen',{}, {evidence:'DEMO-EMPTY'});const r=await agent.run(scope);assert.equal(r.proposal,null);assert(r.findings.some(f=>f.id==='public_aid'));});
test('未実装の労災は通常計算にも自動不支給にも進めない',async t=>{const {store,agent,facts}=setup(t);store.put(scope,'exception_screen',{...facts.exception_screen,work_injury:true},{evidence:'DEMO-WORK'});const r=await agent.run(scope);assert.equal(r.state,'WAITING_STAFF');assert(r.findings.some(f=>f.id==='P26'));assert.equal(r.proposal,null);});
test('同月の現物給付・既支給を控除し二重給付を防ぐ',async t=>{const {store,agent,facts}=setup(t);facts.statements[0].cash-=100000;facts.statements[0].in_kind=100000;store.put(scope,'statements',facts.statements,{evidence:'DEMO-IN-KIND'});store.put(scope,'prior_paid',50000,{evidence:'DEMO-PAID'});assert.equal((await agent.run(scope)).proposal.additional,62570);});
test('多数回は過去11か月・同月重複を除外して判定',async t=>{const {store,agent}=setup(t);const row=month=>({month,kind:'MONTHLY',continuous:true,evidence:'DEMO-HISTORY',amount:1000});store.put(scope,'history',{complete:true,records:['2026-04','2026-04','2026-05','2026-06'].map(row)},{evidence:'DEMO-HISTORY'});const r=await agent.run(scope);assert.equal(r.proposal.multiple,true);assert.equal(r.proposal.additional,255600);});
test('同一明細の重複は計算しない',async t=>{const {store,agent,facts}=setup(t);store.put(scope,'statements',[...facts.statements,...facts.statements],{evidence:'DEMO-DUPLICATE'});assert.equal((await agent.run(scope)).proposal,null);});
test('AI文書作成中に回答が届いたら古い照会を保存しない',async t=>{const {store,facts}=setup(t,{omit:['income']});const agent=new Agent({store,planner:{version:'test',choose:async()=>{store.put(scope,'income',facts.income,{evidence:'DEMO-LATE-ANSWER'});return {option_id:'0',question:'古い照会',source_ids:['guide']};}}});assert.equal((await agent.run(scope)).state,'RETRY_REQUIRED');assert.equal(store.db.prepare('SELECT COUNT(*) n FROM outbox').get().n,0);assert.equal((await agent.run(scope)).state,'MONTHLY_PROPOSAL');});
test('同じ案件を並行実行しても照会案は1件',async t=>{const {store}=setup(t,{omit:['income']});let n=0;const agent=new Agent({store,planner:{version:'test',choose:async()=>({option_id:'0',question:'案'+(++n),source_ids:['guide']})}});const [a,b]=await Promise.all([agent.run(scope),agent.run(scope)]);assert.deepEqual(a,b);assert.equal(store.db.prepare('SELECT COUNT(*) n FROM outbox').get().n,1);});
test('医療機関ごと21,000円未満の負担を合計して対象にしない',async t=>{const {store,agent,facts}=setup(t);const row=facts.statements[0];store.put(scope,'statements',[{...row,total:69997,copay:20999,cash:20999},{...row,id:'DEMO-B',provider:'DEMO-OTHER',total:69997,copay:20999,cash:20999}],{evidence:'DEMO-UNITS'});assert.equal((await agent.run(scope)).proposal.additional,0);});
test('処方元へ薬局分を加えて21,000円判定',async t=>{const {store,agent,facts}=setup(t);const row=facts.statements[0];store.put(scope,'statements',[{...row,setting:'outpatient',total:66667,copay:20000,cash:20000},{...row,id:'DEMO-PHARMACY',provider:'DEMO-PHARMACY',category:'pharmacy',prescriber:row.provider,prescription_category:'medical',setting:'outpatient',total:33333,copay:10000,cash:10000},{...row,id:'DEMO-B',provider:'DEMO-B',total:200000,copay:60000,cash:60000}],{evidence:'DEMO-PRESCRIPTION'});assert.equal((await agent.run(scope)).proposal.additional,9570);});
test('70歳以上一般世帯は個人外来と世帯を順に精算',async t=>{const {store,agent,facts}=setup(t);const person=facts.qualification.members[0];person.age=72;facts.qualification.members.push({...person,id:'DEMO-SPOUSE'});store.put(scope,'qualification',facts.qualification,{evidence:'DEMO-SENIOR'});store.put(scope,'income',{senior:'general'},{evidence:'DEMO-GROUP'});const row=facts.statements[0];store.put(scope,'statements',[{...row,total:490000,copay:49000,cash:49000},{...row,id:'DEMO-B',person:'DEMO-SPOUSE',setting:'outpatient',total:80000,copay:8000,cash:8000},{...row,id:'DEMO-C',person:'DEMO-SPOUSE',setting:'outpatient',total:40000,copay:4000,cash:4000}],{evidence:'DEMO-SENIOR-RECEIPTS'});assert.equal((await agent.run(scope)).proposal.additional,3400);});
test('実ファイルに保存した資料と処理結果から再開できる',async t=>{
 const {mkdtempSync,rmSync}=await import('node:fs');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const folder=mkdtempSync(join(tmpdir(),'benefit-agent-test-'));t.after(()=>rmSync(folder,{recursive:true,force:true}));
 const path=join(folder,'facts.sqlite');let store=new Store(path);seed(store);await new Agent({store}).run(scope);store.close();store=new Store(path);try{assert.equal((await new Agent({store}).run(scope)).proposal.additional,212570);}finally{store.close();}
});
