export const nationalSources=[
 {id:'national-child-order',title:'児童福祉法施行令・小児慢性負担上限',url:'https://www.mhlw.go.jp/web/t_doc?dataId=82061000',from:'2025-04',through:'2027-07',clause:'第22条、22条の4',schemes:['KOKUHO','EMPLOYEE','MUTUAL'],status:'VERIFIED',scope:'認定済み小児慢性区分・難病との世帯配分・先行給付。食事療養は別算定'},
 {id:'national-public-priority',title:'支払基金・医科チェック仕様の公費優先順位',url:'https://www.ssk.or.jp/seikyushiharai/iryokikan/download/index.files/checklogic_ika.pdf',from:'2025-04',through:'2027-07',clause:'PDF91ページ（紙面88）別表2',schemes:['KOKUHO','EMPLOYEE','MUTUAL','LATE_ELDER','MEDICAL_ASSISTANCE'],status:'VERIFIED',scope:'21→52→54→12の優先順位。掲載された他の公費の金額計算対応を意味しない'},
 {id:'national-welfare-cash',title:'生活保護法・医療扶助の方法',url:'https://www.mhlw.go.jp/web/t_doc?dataId=82048000',from:'2025-04',through:'2027-07',clause:'第34条第1項、第7項、第8項',schemes:['MEDICAL_ASSISTANCE','EMPLOYEE','MUTUAL'],status:'VERIFIED',scope:'個別認定済みの金銭給付の精算。立替を自動認定しない'},
 {id:'national-nanbyo-household',title:'難病法施行令・負担上限と世帯按分',url:'https://www.mhlw.go.jp/web/t_doc?dataId=80ab4324&dataType=0&pageNo=1',from:'2025-04',through:'2027-07',clause:'第1条第1項第7号、第2項',schemes:['KOKUHO','EMPLOYEE','MUTUAL','LATE_ELDER'],status:'VERIFIED',scope:'認定済み区分の難病世帯按分・10円未満切捨て。生の所得からの区分判定は対象外'},
 {id:'national-medical-assistance',title:'医療扶助運営要領',url:'https://www.mhlw.go.jp/web/t_doc?dataId=00ta8434&dataType=1',from:'2025-04',through:'2027-07',clause:'他法他施策、医療扶助決定、医療券・本人支払額',schemes:['MEDICAL_ASSISTANCE','EMPLOYEE','MUTUAL'],status:'VERIFIED',scope:'認定済み医療券・他法給付を用いた現物給付。立替は別途個別認定を必須とする'},
 {id:'national-allocation',title:'厚労省 外来年間合算の事務取扱',url:'https://www.mhlw.go.jp/web/t_doc?dataId=00tc3997&dataType=1&pageNo=1',from:'2018-08',through:'2026-07',clause:'第2 3(3) 個人・入院外来・保険者別の按分及び端数調整',schemes:['EMPLOYEE'],status:'VERIFIED',scope:'旧外来年間合算の通常70歳以上世帯。新年間制度へ流用しない'},
 {id:'national-reimbursement',title:'協会けんぽ 療養費',url:'https://www.kyoukaikenpo.or.jp/benefit/medical_expenses/',from:'2018-08',through:'2027-07',clause:'療養費とは・給付の範囲',schemes:['EMPLOYEE'],status:'VERIFIED',scope:'保険者認定費用から自己負担相当額を引く算定'},
 {id:'national-employee',title:'協会けんぽ 高額療養費',url:'https://www.kyoukaikenpo.or.jp/benefit/high_cost_medical_expenses/002/',from:'2026-08',through:'2027-07',clause:'自己負担限度額・保険世帯',schemes:['EMPLOYEE'],status:'VERIFIED',scope:'認定所得区分を用いた法定月額計算'},
 {id:'national-mutual',title:'日本郵政共済組合 法定療養給付',url:'https://www.yuseikyosai.or.jp/tanki/kogaku.html',from:'2026-08',through:'2027-07',clause:'高額療養費（附加給付を除く）',schemes:['MUTUAL'],status:'VERIFIED',scope:'認定所得区分を用いた法定月額計算'},
 {id:'national-annual-qa',title:'厚労省 高額療養費見直しQ&A',url:'https://www.mhlw.go.jp/web/t_doc?dataId=00tc4014&dataType=1',from:'2018-08',through:'2026-07',clause:'3.1.5、3.1.7、3.2.3、3.3.1～3.3.7',schemes:['EMPLOYEE','KOKUHO','LATE_ELDER','MUTUAL'],status:'VERIFIED',scope:'旧外来年間上限。新版の所得・保険変更規程には流用しない'},
 {id:'national-overseas',title:'協会けんぽ 海外療養費',url:'https://www.kyoukaikenpo.or.jp/benefit/overseas_medical_expenses/',from:'2018-08',through:'2027-07',clause:'給付対象・給付内容',schemes:['EMPLOYEE'],status:'VERIFIED',scope:'確認済み国内相当額・換算額・自己負担額による療養費本体'},
 {id:'national-overseas-kokuho',title:'厚労省 海外療養費の支給申請及び審査',url:'https://www.mhlw.go.jp/web/t_doc?dataId=00tc1870&dataType=1&pageNo=1',from:'2018-08',through:'2027-07',clause:'国保 海外療養費事務取扱',schemes:['KOKUHO'],status:'REVIEWING',scope:'申請確認。換算・算定規程の確認は別途必要'},
 {id:'national-orthosis',title:'厚労省 治療用装具に係る療養費',url:'https://www.mhlw.go.jp/bunya/iryouhoken/iryouhoken13/01-03.html',from:'2018-08',through:'2027-07',clause:'療養費支給認定・算定通知一覧',schemes:['KOKUHO','EMPLOYEE','MUTUAL','LATE_ELDER'],status:'REVIEWING',scope:'装具価格査定を行わず保険者認定費用を使用'},
 {id:'national-nanbyo',title:'厚労省 難病に係る自己負担上限額',url:'https://www.mhlw.go.jp/content/10905000/001405501.pdf',from:'2025-04',through:'2027-07',clause:'24ページ 自己負担上限額',schemes:['KOKUHO','EMPLOYEE','MUTUAL','LATE_ELDER'],status:'VERIFIED',scope:'認定証の所得区分・限度額を用いる単独受給者・対象診療のみ'},
 {id:'national-psychiatric',title:'厚労省 自立支援医療の患者負担',url:'https://www.mhlw.go.jp/content/001446684.pdf',from:'2025-04',through:'2027-03',clause:'47ページ 精神通院の負担割合と経過特例期限',schemes:['KOKUHO','EMPLOYEE','MUTUAL','LATE_ELDER'],status:'VERIFIED',scope:'認定証の限度額。特例を2027年4月以降へ延長しない'},
 {id:'national-public-order',title:'厚労省 公費負担医療に関する費用徴収基準',url:'https://www.mhlw.go.jp/web/t_doc?dataId=00tc3983&dataType=1&pageNo=1',from:'2018-08',through:'2027-07',clause:'保険給付・公費徴収の調整',schemes:['KOKUHO','EMPLOYEE','MUTUAL','LATE_ELDER'],status:'REVIEWING',scope:'旧金額は使用しない。複数公費・非対象診療併用は保留'},
 {id:'national-accident',title:'協会けんぽ 第三者行為による傷病届',url:'https://www.kyoukaikenpo.or.jp/benefit/accident/',from:'2018-08',through:'2027-07',clause:'保険給付・損害賠償・求償',schemes:['EMPLOYEE'],status:'VERIFIED',scope:'確認済み同一事由の給付対応控除額のみ。賠償責任を判定しない'},
 {id:'national-labor',title:'厚労省 健康保険から労災への切替',url:'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000154463.html',from:'2018-08',through:'2027-07',clause:'2-1 健康保険証を使って受診した場合',schemes:['LABOR'],status:'VERIFIED',scope:'認定済み療養費と本人負担・保険者間精算を区別'}
];
export function applicableSources(month){return nationalSources.filter(s=>s.status==='VERIFIED'&&s.from<=month&&s.through>=month);}
